#!/bin/bash

check=$(xrandr | awk '/^LVDS/ {print $1}')
match="LVDS1"

if [ "$check" = "$match" ]; then
    match="LVDS1"
else
    match="LVDS-1"
fi

xfce4-terminal --command="xrandr --output $match --panning 1366x768 --scale 1x1"
sleep 0.5
xfce4-terminal --command="xrandr --output $match --panning 1920x1080 --scale 1.406x1.406"
