#!/bin/sh

# The famous "get a menu of emojis to copy" script.

# Source dmenurc if it exists and sets a default if it isn't present
if [ -f $HOME/.dmenurc ]; then
    . $HOME/.dmenurc
else
    DMENU='dmenu -i'
fi

# Get user selection via dmenu from emoji file.
chosen=$(cut -d ';' -f1 ~/emoji | $DMENU -p "Emoji: " -l 10 -fn 'JoyPixels:bold:pixelsize=24:antialias=true:autohint=true' | sed "s/ .*//")

# Exit if none chosen.
[ -z "$chosen" ] && exit

# If you run this command with an argument, it will automatically insert the
# character. Otherwise, show a message that the emoji has been copied.
if [ -n "$1" ]; then
	xdotool type "$chosen"
else
	printf "$chosen" | xclip -selection clipboard
	notify-send "'$chosen' copied to clipboard." &
fi
