#!/bin/bash

check=$(xrandr | awk '/^LVDS/ {print $1}')
match="LVDS1"
change_win="wmctrl -i -r `wmctrl -l | grep "Task Manager"` -e 0,0,0,1366,587"

if [ "$check" = "$match" ]; then
    match="LVDS1"
else
    match="LVDS-1"
fi

xfce4-terminal --command="xrandr --output $match --panning 1366x768 --scale 1x1" && $change_win
